package com.client.belarosa.service;

import java.text.ParseException;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.client.belarosa.domain.Categoria;
import com.client.belarosa.domain.Imagem;
import com.client.belarosa.domain.Produto;
import com.client.belarosa.domain.SubCategoria;
import com.client.belarosa.repositories.CategoriaRepository;
import com.client.belarosa.repositories.ImagemRepository;
import com.client.belarosa.repositories.ProdutoRepository;
import com.client.belarosa.repositories.SubCategoriaRepository;

@Service
public class DBInitialService {
	
	@Autowired
	CategoriaRepository categoria_repository;
	
	@Autowired
	SubCategoriaRepository sub_categoria_repository;
	
	@Autowired
	ProdutoRepository produto_repository;
	
	@Autowired
	ImagemRepository imagem_repository;
	
	
    public void instantiateTestDataBase () throws ParseException {
        //Categoria cat1 = new Categoria(null, "Acessorios"); 
    	Categoria cat2 = new Categoria(null, "Cosmeticos"); 	
    	Categoria cat3 = new Categoria(null, "Bolsas");
    	Categoria cat4 = new Categoria(null, "Maquiagens");
    	Categoria cat5 = new Categoria(null, "Calçados");
    	Categoria cat6 = new Categoria(null, "Oculos");
    	Categoria cat7 = new Categoria(null, "Roupas");
    	Categoria cat8 = new Categoria(null, "Utensilios");
    	Categoria cat9 = new Categoria(null, "Adulto");
    	Categoria cat10 = new Categoria(null, "Cuidado Pessoal");
    	
    	SubCategoria subcat1 = new SubCategoria(null, "Esmaltes", cat2);
    	SubCategoria subcat3 = new SubCategoria(null, "Xampus", cat10); 
    	SubCategoria subcat4 = new SubCategoria(null, "Cremes hidratantes", cat2); 
    	SubCategoria subcat5 = new SubCategoria(null, "Perfumes", cat2); 
    	SubCategoria subcat6 = new SubCategoria(null, "Desodorantes", cat10);  	
    	SubCategoria subcat8 = new SubCategoria(null, "Loções", cat10);
    	SubCategoria subcat9 = new SubCategoria(null, "Demaquilantes", cat4);
    	SubCategoria subcat10 = new SubCategoria(null, "Carteiras", cat3);
    	SubCategoria subcat11 = new SubCategoria(null, "Viagens",cat3); 
    	SubCategoria subcat12 = new SubCategoria(null, "Mochilas", cat3); 
    	SubCategoria subcat13 = new SubCategoria(null, "Bolsas de Colo", cat3); 
    	SubCategoria subcat14 = new SubCategoria(null, "Alças", cat3); 
    	SubCategoria subcat15 = new SubCategoria(null, "Bolsas de Mão", cat3); 
    	SubCategoria subcat16 = new SubCategoria(null, "Pinceis", cat4);
    	SubCategoria subcat17 = new SubCategoria(null, "Esponjas", cat4); 
    	SubCategoria subcat18 = new SubCategoria(null, "Blush", cat4); 
    	SubCategoria subcat19 = new SubCategoria(null, "Sombras", cat4); 
    	SubCategoria subcat20 = new SubCategoria(null, "Lapis", cat4); 
    	SubCategoria subcat21 = new SubCategoria(null, "Delineadores", cat4); 
    	SubCategoria subcat22 = new SubCategoria(null, "Sobrancelhas", cat4); 
    	SubCategoria subcat23 = new SubCategoria(null, "Oculos de Sol",cat6);
    	SubCategoria subcat24 = new SubCategoria(null, "Oculos infântil", cat6); 
    	SubCategoria subcat25 = new SubCategoria(null, "Fantasia", cat9); 
    	SubCategoria subcat26 = new SubCategoria(null, "Acessorios Femininos", cat9); 
    	SubCategoria subcat27 = new SubCategoria(null, "Proteção", cat9); 
    	SubCategoria subcat28 = new SubCategoria(null, "Sabonetes", cat10);
    	SubCategoria subcat29 = new SubCategoria(null, "Condicionadores", cat10); 
    	SubCategoria subcat31 = new SubCategoria(null, "Hidratantes de pele", cat10); 
    	SubCategoria subcat32 = new SubCategoria(null, "Hidratantes de cabelo", cat10);
    	SubCategoria subcat33 = new SubCategoria(null, "Escovas", cat10); 
    	SubCategoria subcat34 = new SubCategoria(null, "Óleo corporal", cat10);
    	SubCategoria subcat35 = new SubCategoria(null, "Sapatos casual",cat5);
    	SubCategoria subcat36 = new SubCategoria(null, "Sapatos de caminhada",cat5);
    	SubCategoria subcat37 = new SubCategoria(null, "Higiene bucal", cat10);
    	SubCategoria subcat38 = new SubCategoria(null, "Limpeza do corpo", cat10);
    	SubCategoria subcat39 = new SubCategoria(null, "Penteados do cabelo", cat10);
    	SubCategoria subcat40 = new SubCategoria(null, "Batons", cat2);
    	SubCategoria subcat41 = new SubCategoria(null, "Acadêmia", cat7);
    	SubCategoria subcat42 = new SubCategoria(null, "Roupas de dormir", cat7);
    	SubCategoria subcat43 = new SubCategoria(null, "Cuecas", cat7);
    	SubCategoria subcat44 = new SubCategoria(null, "Calcinhas", cat7);
    	SubCategoria subcat45 = new SubCategoria(null, "Xicaras", cat8);
    	SubCategoria subcat46 = new SubCategoria(null, "Garrafas", cat8);
    	SubCategoria subcat47 = new SubCategoria(null, "Talheres", cat8);
    	
    	cat2.getSub_categorias().addAll(Arrays.asList(subcat1, subcat4, subcat5, subcat40));
    	cat3.getSub_categorias().addAll(Arrays.asList(subcat10, subcat11, subcat12, subcat13, subcat14, subcat15));
    	cat4.getSub_categorias().addAll(Arrays.asList(subcat9, subcat16, subcat17, subcat18, subcat19, subcat20, subcat21, subcat22));
    	cat5.getSub_categorias().addAll(Arrays.asList(subcat35, subcat36));
    	cat6.getSub_categorias().addAll(Arrays.asList(subcat23, subcat24));
    	cat7.getSub_categorias().addAll(Arrays.asList(subcat41, subcat42, subcat43, subcat44));
    	cat8.getSub_categorias().addAll(Arrays.asList(subcat45, subcat46, subcat47));
    	cat9.getSub_categorias().addAll(Arrays.asList(subcat25, subcat26, subcat27));
    	cat10.getSub_categorias().addAll(Arrays.asList(subcat3, subcat6, subcat8, subcat28, subcat29, subcat31, subcat32, subcat33, subcat34, subcat37, subcat38, subcat39));
    	
    	String descr1 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr2 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr3 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr4 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr5 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr6 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr7 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr8 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr9 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr10 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr11 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr12 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr13 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr14 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr15 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr16 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr17 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr18 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr19 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr20 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr21 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr22 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr23 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr24 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr25 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr26 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr27 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr28 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr29 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";
    	String descr30 = "Essa é uma descrição deste produto, poder ser detalhado ou ate mesmo resumo, desde que atenda o maximo 1000 caracteres";

    	Produto prod1 = new Produto(null, "Carteita Victorino em couro", 35.99, descr1);
    	Produto prod2 = new Produto(null, "Bolsa Santa Lolla Baú Marrom", 279.99, descr2);
    	Produto prod3 = new Produto(null, "Kit pincel maquiagem", 199.99, descr3);
    	Produto prod4 = new Produto(null, "Bolsa Feminina Grande Tote Transversal Couro Ecológico", 89.65, descr4);
    	Produto prod5 = new Produto(null, "Sapato Feminino Coleção Verão", 99.99, descr5);
    	Produto prod6 = new Produto(null, "Escova de cabelo fenimina", 14.99, descr6);
    	Produto prod7 = new Produto(null, "Kit escova + pedra + sabonete Marseller", 24.50,descr7);
    	Produto prod8 = new Produto(null, "Sabonte Evex para pele ressecada", 5.99, descr8);
    	Produto prod9 = new Produto(null, "Sabonete amêndoas e damasco", 14.99, descr9);
    	Produto prod10 = new Produto(null, "Sabonete atersanal mel de abelhas", 6.45, descr10);
    	Produto prod11 = new Produto(null, "Sabonete atersanal café", 6.45, descr11);
    	Produto prod12 = new Produto(null, "Baton Mary Kay vermelho sol", 22.50, descr12);
    	Produto prod13 = new Produto(null, "Kit 3 unidades Baton Mary Kay", 45.90, descr13);
    	Produto prod14 = new Produto(null, "Pincel de maquigem 10cm", 4.99, descr14);
    	Produto prod15 = new Produto(null, "Baton Mac 48hrs de efeito brilhante", 69.99, descr15);
    	Produto prod16 = new Produto(null, "Kit Shampoo + Condicionador + Creme de hidratação Loreal para cabelos secos", 39.99, descr16);
    	Produto prod17 = new Produto(null, "Kit de maquiagem Melger - Kit em promoção", 12.99, descr17);
    	Produto prod18 = new Produto(null, "Baton Mary kay Sempre Vermelho", 17.99, descr18);
    	Produto prod19 = new Produto(null, "Tênis infântil Vingadores nº 23/24", 99.99, descr19);
    	Produto prod20 = new Produto(null, "Tênis Nike Intense nº 41/42", 169.99, descr20);
    	Produto prod21 = new Produto(null, "Tênis Nike feminino Roll rosa nº 27/28", 145.99, descr21);
    	Produto prod22 = new Produto(null, "Creme de hidratação Royal Siam avelã e cacau", 34.99, descr22);		
    	Produto prod23 = new Produto(null, "Oléo corporal Max Coorp frutas silvestres ", 24.99, descr23);
    	Produto prod24 = new Produto(null, "Tênis Nike Masculino Roll azul nº 37/38", 145.99, descr24);
    	Produto prod25 = new Produto(null, "Tênis Meindl Branco Azul nº 42/43", 99.99, descr25);
    	Produto prod26 = new Produto(null, "Tênis Meindl Verde Amarelo Branco nº 42/43", 99.99, descr26);
    	Produto prod27 = new Produto(null, "Fantasia Noturna Dracula",129.90, descr27);
    	Produto prod28 = new Produto(null, "Rabo de gato", 10.00, descr28);
    	Produto prod29 = new Produto(null, "Fantasia de enfermeira com tapa olho", 177.00, descr29);
    	Produto prod30 = new Produto(null, "Oculos solar feminino", 90.00, descr30);
    	
    	Imagem img1_prod1 = new Imagem(null, "https://cdn.pixabay.com/photo/2019/06/09/15/58/wallet-4262349_1280.png");
    	Imagem img1_prod2  = new Imagem(null, "https://cdn.pixabay.com/photo/2017/09/15/08/01/leather-case-2751381_1280.png");
    	Imagem img1_prod3  = new Imagem(null, "https://cdn.pixabay.com/photo/2016/10/06/21/11/brush-1720073_960_720.jpg");
    	Imagem img1_prod4  = new Imagem(null, "https://cdn.pixabay.com/photo/2017/09/08/07/59/bag-2728000_960_720.png");
    	Imagem img1_prod5  = new Imagem(null, "https://cdn.pixabay.com/photo/2013/09/01/18/12/womens-shoes-178163_960_720.jpg");
    	Imagem img1_prod6  = new Imagem(null, "https://cdn.pixabay.com/photo/2012/12/09/13/41/comb-69154_1280.jpg");
    	Imagem img1_prod7  = new Imagem(null, "https://cdn.pixabay.com/photo/2016/01/10/16/30/toilet-1132083_1280.jpg");
    	Imagem img1_prod8  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/05/06/02/11/soap-754837_1280.jpg");
    	Imagem img1_prod9  = new Imagem(null, "https://cdn.pixabay.com/photo/2017/05/22/07/34/soap-2333391_1280.jpg");
    	Imagem img1_prod10  = new Imagem(null, "https://cdn.pixabay.com/photo/2016/05/31/21/44/soap-1427929_1280.jpg");
    	Imagem img1_prod11  = new Imagem(null, "https://cdn.pixabay.com/photo/2018/04/03/03/37/coffee-3285819_1280.jpg");
    	Imagem img1_prod12  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/04/20/23/21/makeup-732405_1280.jpg");
    	Imagem img1_prod13  = new Imagem(null, "https://cdn.pixabay.com/photo/2017/08/05/19/28/lipstick-2585174_1280.jpg");
    	Imagem img1_prod14  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/07/01/03/16/brush-827150_1280.jpg");
    	Imagem img1_prod15  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/09/20/02/06/lipstick-947895_1280.jpg");
    	Imagem img1_prod16  = new Imagem(null, "https://cdn.pixabay.com/photo/2019/10/11/12/19/hair-care-4541744_1280.jpg");
    	Imagem img1_prod17  = new Imagem(null, "https://cdn.pixabay.com/photo/2020/04/25/09/10/cosmetics-5090011_1280.jpg");
    	Imagem img1_prod18  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/04/20/23/21/makeup-732405_1280.jpg");
    	Imagem img1_prod19  = new Imagem(null, "https://cdn.pixabay.com/photo/2016/06/03/17/35/shoes-1433925_1280.jpg");
    	Imagem img1_prod20  = new Imagem(null, "https://cdn.pixabay.com/photo/2014/05/18/11/26/shoes-346986_1280.jpg");
    	Imagem img1_prod21  = new Imagem(null, "https://cdn.pixabay.com/photo/2014/06/18/18/41/running-shoe-371624_1280.jpg");
    	Imagem img1_prod22  = new Imagem(null, "https://cdn.pixabay.com/photo/2014/05/25/11/21/thai-shampoo-353536_1280.jpg");
    	Imagem img1_prod23  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/07/01/03/13/shampoo-827141_1280.jpg");
    	Imagem img1_prod24  = new Imagem(null, "https://cdn.pixabay.com/photo/2014/06/18/18/42/running-shoe-371625_1280.jpg");
    	Imagem img1_prod25  = new Imagem(null, "https://cdn.pixabay.com/photo/2014/04/10/18/39/running-shoe-321199_1280.jpg");
    	Imagem img1_prod26  = new Imagem(null, "https://cdn.pixabay.com/photo/2015/02/09/13/40/shoe-629643_1280.jpg");
    	Imagem img1_prod27  = new Imagem(null, "https://cdn.pixabay.com/photo/2022/11/24/06/59/vampire-7613622_1280.jpg");
    	Imagem img1_prod28  = new Imagem(null, "https://cdn.pixabay.com/photo/2021/05/09/12/46/cat-costume-6240780_1280.jpg");
    	Imagem img1_prod29  = new Imagem(null, "https://cdn.pixabay.com/photo/2020/11/27/05/57/woman-5780971_1280.jpg");
    	Imagem img1_prod30  = new Imagem(null, "https://cdn.pixabay.com/photo/2016/05/09/19/12/sunglasses-1382261_960_720.jpg");
    	
    	img1_prod1.getProdutos().addAll(Arrays.asList(prod1));
    	img1_prod2.getProdutos().addAll(Arrays.asList(prod2));
    	img1_prod3.getProdutos().addAll(Arrays.asList(prod3));
    	img1_prod4.getProdutos().addAll(Arrays.asList(prod4));
    	img1_prod5.getProdutos().addAll(Arrays.asList(prod5));
    	img1_prod6.getProdutos().addAll(Arrays.asList(prod6));
    	img1_prod7.getProdutos().addAll(Arrays.asList(prod7));
    	img1_prod8.getProdutos().addAll(Arrays.asList(prod8));
    	img1_prod9.getProdutos().addAll(Arrays.asList(prod9));
    	img1_prod10.getProdutos().addAll(Arrays.asList(prod10));
    	img1_prod11.getProdutos().addAll(Arrays.asList(prod11));
    	img1_prod12.getProdutos().addAll(Arrays.asList(prod12));
    	img1_prod13.getProdutos().addAll(Arrays.asList(prod13));
    	img1_prod14.getProdutos().addAll(Arrays.asList(prod14));
    	img1_prod15.getProdutos().addAll(Arrays.asList(prod15));
    	img1_prod16.getProdutos().addAll(Arrays.asList(prod16));
    	img1_prod17.getProdutos().addAll(Arrays.asList(prod17));
    	img1_prod18.getProdutos().addAll(Arrays.asList(prod18));
    	img1_prod19.getProdutos().addAll(Arrays.asList(prod19));
    	img1_prod20.getProdutos().addAll(Arrays.asList(prod20));
    	img1_prod21.getProdutos().addAll(Arrays.asList(prod21));
    	img1_prod22.getProdutos().addAll(Arrays.asList(prod22));
    	img1_prod23.getProdutos().addAll(Arrays.asList(prod23));
    	img1_prod24.getProdutos().addAll(Arrays.asList(prod24));
    	img1_prod25.getProdutos().addAll(Arrays.asList(prod25));
    	img1_prod26.getProdutos().addAll(Arrays.asList(prod26));
    	img1_prod27.getProdutos().addAll(Arrays.asList(prod27));
    	img1_prod28.getProdutos().addAll(Arrays.asList(prod28));
    	img1_prod29.getProdutos().addAll(Arrays.asList(prod29));
    	img1_prod30.getProdutos().addAll(Arrays.asList(prod30));
    	
    	prod1.getImagens().addAll(Arrays.asList(img1_prod1));
    	prod2.getImagens().addAll(Arrays.asList(img1_prod2));
    	prod3.getImagens().addAll(Arrays.asList(img1_prod3));
    	prod4.getImagens().addAll(Arrays.asList(img1_prod4));
    	prod5.getImagens().addAll(Arrays.asList(img1_prod5));
    	prod6.getImagens().addAll(Arrays.asList(img1_prod6));
    	prod7.getImagens().addAll(Arrays.asList(img1_prod7));
    	prod8.getImagens().addAll(Arrays.asList(img1_prod8));
    	prod9.getImagens().addAll(Arrays.asList(img1_prod9));
    	prod10.getImagens().addAll(Arrays.asList(img1_prod10));
    	prod11.getImagens().addAll(Arrays.asList(img1_prod11));
    	prod12.getImagens().addAll(Arrays.asList(img1_prod12));
    	prod13.getImagens().addAll(Arrays.asList(img1_prod13));
    	prod14.getImagens().addAll(Arrays.asList(img1_prod14));
    	prod15.getImagens().addAll(Arrays.asList(img1_prod15));
    	prod16.getImagens().addAll(Arrays.asList(img1_prod16));
    	prod17.getImagens().addAll(Arrays.asList(img1_prod17));
    	prod18.getImagens().addAll(Arrays.asList(img1_prod18));
    	prod19.getImagens().addAll(Arrays.asList(img1_prod19));
    	prod20.getImagens().addAll(Arrays.asList(img1_prod20));
    	prod21.getImagens().addAll(Arrays.asList(img1_prod21));
    	prod22.getImagens().addAll(Arrays.asList(img1_prod22));
    	prod23.getImagens().addAll(Arrays.asList(img1_prod23));
    	prod24.getImagens().addAll(Arrays.asList(img1_prod24));
    	prod25.getImagens().addAll(Arrays.asList(img1_prod25));
    	prod26.getImagens().addAll(Arrays.asList(img1_prod26));
    	prod27.getImagens().addAll(Arrays.asList(img1_prod27));
    	prod28.getImagens().addAll(Arrays.asList(img1_prod28));
    	prod29.getImagens().addAll(Arrays.asList(img1_prod29));
    	prod30.getImagens().addAll(Arrays.asList(img1_prod30));	
    	
    	prod1.getCategorias().addAll(Arrays.asList(cat3));
    	prod2.getCategorias().addAll(Arrays.asList(cat3));
    	prod3.getCategorias().addAll(Arrays.asList(cat4));
    	prod4.getCategorias().addAll(Arrays.asList(cat3));
    	prod5.getCategorias().addAll(Arrays.asList(cat5));
    	prod6.getCategorias().addAll(Arrays.asList(cat10));
    	prod7.getCategorias().addAll(Arrays.asList(cat10));
    	prod8.getCategorias().addAll(Arrays.asList(cat10));
    	prod9.getCategorias().addAll(Arrays.asList(cat10));
    	prod10.getCategorias().addAll(Arrays.asList(cat10));
    	prod11.getCategorias().addAll(Arrays.asList(cat10));
    	prod12.getCategorias().addAll(Arrays.asList(cat2));
    	prod13.getCategorias().addAll(Arrays.asList(cat2));
    	prod14.getCategorias().addAll(Arrays.asList(cat4));
    	prod15.getCategorias().addAll(Arrays.asList(cat2));
    	prod16.getCategorias().addAll(Arrays.asList(cat10));
    	prod17.getCategorias().addAll(Arrays.asList(cat4));
    	prod18.getCategorias().addAll(Arrays.asList(cat2));
    	prod19.getCategorias().addAll(Arrays.asList(cat5));
    	prod20.getCategorias().addAll(Arrays.asList(cat5));
    	prod21.getCategorias().addAll(Arrays.asList(cat5));
    	prod22.getCategorias().addAll(Arrays.asList(cat10));
    	prod23.getCategorias().addAll(Arrays.asList(cat10));
    	prod24.getCategorias().addAll(Arrays.asList(cat5));
    	prod25.getCategorias().addAll(Arrays.asList(cat5));
    	prod26.getCategorias().addAll(Arrays.asList(cat5));
    	prod27.getCategorias().addAll(Arrays.asList(cat9));
    	prod28.getCategorias().addAll(Arrays.asList(cat9));
    	prod29.getCategorias().addAll(Arrays.asList(cat9));
    	prod30.getCategorias().addAll(Arrays.asList(cat6));
    
		prod1.getSub_categorias().addAll(Arrays.asList(subcat10));
		prod2.getSub_categorias().addAll(Arrays.asList(subcat13));
		prod3.getSub_categorias().addAll(Arrays.asList(subcat16));
		prod4.getSub_categorias().addAll(Arrays.asList(subcat14));
		prod5.getSub_categorias().addAll(Arrays.asList(subcat35));
		prod6.getSub_categorias().addAll(Arrays.asList(subcat33));
		prod7.getSub_categorias().addAll(Arrays.asList(subcat33));
		prod8.getSub_categorias().addAll(Arrays.asList(subcat28));
		prod9.getSub_categorias().addAll(Arrays.asList(subcat28));
		prod10.getSub_categorias().addAll(Arrays.asList(subcat28));
		prod11.getSub_categorias().addAll(Arrays.asList(subcat28));
		prod12.getSub_categorias().addAll(Arrays.asList(subcat40));
		prod13.getSub_categorias().addAll(Arrays.asList(subcat40));
		prod14.getSub_categorias().addAll(Arrays.asList(subcat16));
		prod15.getSub_categorias().addAll(Arrays.asList(subcat40));
		prod16.getSub_categorias().addAll(Arrays.asList(subcat3));
		prod17.getSub_categorias().addAll(Arrays.asList(subcat20));
		prod18.getSub_categorias().addAll(Arrays.asList(subcat40));
		prod19.getSub_categorias().addAll(Arrays.asList(subcat35));
		prod20.getSub_categorias().addAll(Arrays.asList(subcat36));
		prod21.getSub_categorias().addAll(Arrays.asList(subcat36));
		prod22.getSub_categorias().addAll(Arrays.asList(subcat31));
		prod23.getSub_categorias().addAll(Arrays.asList(subcat31));
		prod24.getSub_categorias().addAll(Arrays.asList(subcat36));
		prod25.getSub_categorias().addAll(Arrays.asList(subcat36));
		prod26.getSub_categorias().addAll(Arrays.asList(subcat36));
		prod27.getSub_categorias().addAll(Arrays.asList(subcat25));
		prod28.getSub_categorias().addAll(Arrays.asList(subcat26));
		prod29.getSub_categorias().addAll(Arrays.asList(subcat25));
		prod30.getSub_categorias().addAll(Arrays.asList(subcat23));

		cat2.getProdutos().addAll(Arrays.asList(prod12, prod13, prod15, prod18));
		cat3.getProdutos().addAll(Arrays.asList(prod1, prod2, prod4));
		cat4.getProdutos().addAll(Arrays.asList(prod3, prod14, prod17));
		cat5.getProdutos().addAll(Arrays.asList(prod5,prod19, prod20, prod21, prod24,prod25, prod26));
		cat6.getProdutos().addAll(Arrays.asList(prod30));
		cat9.getProdutos().addAll(Arrays.asList(prod27,prod28,prod29));
		cat10.getProdutos().addAll(Arrays.asList(prod6, prod7, prod8, prod9, prod10, prod11, prod16, prod22, prod23));

		subcat3.getProdutos().addAll(Arrays.asList(prod16));
		subcat10.getProdutos().addAll(Arrays.asList(prod1));
		subcat13.getProdutos().addAll(Arrays.asList(prod2));
		subcat14.getProdutos().addAll(Arrays.asList(prod4));
		subcat16.getProdutos().addAll(Arrays.asList(prod3, prod14));
		subcat20.getProdutos().addAll(Arrays.asList(prod17));
		subcat25.getProdutos().addAll(Arrays.asList(prod27, prod29));
		subcat26.getProdutos().addAll(Arrays.asList(prod28));
		subcat28.getProdutos().addAll(Arrays.asList(prod8, prod9, prod10 , prod11));
		subcat31.getProdutos().addAll(Arrays.asList(prod22, prod23));
		subcat33.getProdutos().addAll(Arrays.asList(prod6, prod7));
		subcat35.getProdutos().addAll(Arrays.asList(prod5, prod19));
		subcat36.getProdutos().addAll(Arrays.asList(prod20, prod21, prod24, prod25, prod26));
		subcat40.getProdutos().addAll(Arrays.asList(prod12, prod14, prod15, prod18));
		
		categoria_repository.saveAll(Arrays.asList(cat2, cat3, cat4, cat5, cat6, cat7, cat8, cat9, cat10));
    	sub_categoria_repository.saveAll(Arrays.asList(subcat1, subcat3, subcat4, subcat5, subcat6, subcat8, subcat9, subcat10, subcat11, subcat12, subcat13, subcat14, subcat15, subcat16, subcat17, subcat18, subcat19, subcat20, subcat21, subcat22, subcat23, subcat24, subcat25, subcat26, subcat27, subcat28, subcat29, subcat31, subcat32, subcat33, subcat34, subcat35, subcat36, subcat37, subcat38, subcat39, subcat40, subcat41, subcat42, subcat43, subcat44, subcat45, subcat46, subcat47));
    	imagem_repository.saveAll(Arrays.asList(img1_prod1,img1_prod2, img1_prod3, img1_prod4, img1_prod5, img1_prod6,img1_prod7, img1_prod8, img1_prod9, img1_prod10, img1_prod11,img1_prod12, img1_prod13, img1_prod14, img1_prod15, img1_prod16,img1_prod17, img1_prod18, img1_prod19, img1_prod20, img1_prod21,img1_prod22, img1_prod23, img1_prod24, img1_prod25, img1_prod26,img1_prod27, img1_prod28, img1_prod29, img1_prod30));
    	produto_repository.saveAll(Arrays.asList(prod1, prod2, prod3, prod4, prod5, prod6, prod7, prod8, prod9, prod10, prod11, prod12, prod13, prod14, prod15, prod16, prod17, prod18, prod19, prod20, prod21, prod22, prod23, prod24, prod25, prod26, prod27, prod28, prod29, prod30));	
    }
}
